swagger: "2.0"
info:
  description: "Fetch paginated comparison history."
  version: "1.0.0"
  title: "History API"
paths:
  /api/history:
    get:
      tags:
        - "History"
      summary: "Get comparison history"
      description: "Fetch paginated history of file comparisons. Admins can view all comparisons; regular users can view their own."
      parameters:
        - name: "page"
          in: "query"
          description: "Page number for pagination"
          required: false
          type: "integer"
          default: 1
      responses:
        200:
          description: "Successful response with history data"
          schema:
            type: "object"
            properties:
              history:
                type: "array"
                items:
                  type: "object"
                  properties:
                    id:
                      type: "integer"
                    file1:
                      type: "string"
                    file2:
                      type: "string"
                    similarity:
                      type: "number"
                    comparison_date:
                      type: "string"
                      format: "date-time"
                    file1_upload_date:
                      type: "string"
                      format: "date-time"
                    file2_upload_date:
                      type: "string"
                      format: "date-time"
                    highlighted_content1:
                      type: "string"
                    highlighted_content2:
                      type: "string"
                    user:
                      type: "string"
              page:
                type: "integer"
              total_pages:
                type: "integer"
              is_admin:
                type: "boolean"
        500:
          description: "Error fetching history"
