# Generated by Django 5.0.8 on 2025-02-07 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
                ('highlighted_content1', models.TextField()),
                ('highlighted_content2', models.TextField()),
                ('compared_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_file1', to='filecompare.file')),
                ('file2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_file2', to='filecompare.file')),
            ],
        ),
        migrations.DeleteModel(
            name='ComparisonHistory',
        ),
    ]
