# Generated by Django 5.0.8 on 2025-02-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0003_comparison_similarity_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comparison',
            options={'ordering': ['-compared_at']},
        ),
        migrations.AlterField(
            model_name='comparison',
            name='similarity_category',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
    ]
