# Generated by Django 5.0.8 on 2025-02-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0004_alter_comparison_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='sequence_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
