# Generated by Django 5.0.8 on 2025-02-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0005_comparison_sequence_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='sequence_number',
        ),
    ]
