# Generated by Django 5.0.8 on 2025-02-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0006_remove_comparison_sequence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='session_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
