# Generated by Django 5.0.8 on 2025-02-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0007_comparison_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='name_of_comparison',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
