# Generated by Django 5.0.8 on 2025-02-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0008_comparison_name_of_comparison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='session_id',
        ),
    ]
