# Generated by Django 5.0.8 on 2025-02-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0009_remove_comparison_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='session_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
