# Generated by Django 5.0.8 on 2025-02-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0010_comparison_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='session_id',
        ),
    ]
