# Generated by Django 5.0.8 on 2025-02-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0013_remove_comparison_similarity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='comparison_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
