# Generated by Django 5.0.8 on 2025-03-26 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0014_alter_comparison_comparison_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='compared_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='comparison_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['user'], name='filecompare_user_id_45bf36_idx'),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['compared_at'], name='filecompare_compare_3118e0_idx'),
        ),
    ]
